language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer install

matrix:
    fast_finish: true
    include:
        -
            php: 5.4
            env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - composer test ${PHPUNIT_FLAGS}

after_success:
    - if [[ "${COVERAGE}" = true ]]; then php vendor/bin/coveralls -v; fi
